import React from 'react';
import { Box, Typography, Divider } from '@mui/material';

/**
 * Footer component for the print/PDF view
 */
const PrintFooter: React.FC = () => {
  const currentYear = new Date().getFullYear();
  
  return (
    <Box sx={{ mt: 6, pt: 2 }}>
      <Divider sx={{ mb: 2 }} />
      
      <Typography variant="body2" align="center" color="text.secondary" sx={{ mb: 1 }}>
        This report was generated by CommitIQ.ai, a platform that analyzes GitHub activity to provide 
        objective insights into developer skills and contributions.
      </Typography>
      
      <Typography variant="caption" align="center" display="block" color="text.secondary">
        © {currentYear} CommitIQ. All rights reserved. Generated on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
      </Typography>
    </Box>
  );
};

export default PrintFooter; 